services:
  fastapi_blue:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fastapi_blue
    env_file:
      - .env
    environment:
      - APP_ENV=production
    restart: always

  fastapi_green:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fastapi_green
    env_file:
      - .env
    environment:
      - APP_ENV=staging
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "4444:4444"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - fastapi_blue
      - fastapi_green
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
