name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push blue container
        uses: docker/build-push-action@v5
        with:
          context: ./app/docker
          push: true
          tags: kimtaekgwan/fastapi_blue:latest

      - name: Build and push green container
        uses: docker/build-push-action@v5
        with:
          context: ./app/docker
          push: true
          tags: kimtaekgwan/fastapi_green:latest

      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_SSH_PORT }}
          script: |
            cd /home/ubuntu/project
            echo "${{ secrets.ENV_FILE }}" > .env
            docker-compose pull
            docker-compose up -d --no-deps fastapi_blue fastapi_green
